server:
  port: 8081
spring:
  datasource:
        driverClassName:  com.mysql.jdbc.Driver
        url: jdbc:mysql://47.105.169.84:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 1314520
  jpa:
    database: mysql
